-- Intentionally empty.
--
-- This migration and 20260903111619_manager_quests both created the "quest" table. Applied in
-- timestamp order, the second one hit `ERROR: relation "quest" already exists` and stopped the
-- run — so `prisma migrate deploy` failed on every fresh database, and no new environment
-- could be provisioned at all. It never applied anywhere, which is why its body can be
-- replaced rather than compensated for with a follow-up migration.
--
-- 20260903111619 is the one kept, because it is the one that matches the schema: it declares
-- the "QuestStatus" enum type and types "quest"."status" as that enum, which is what
-- `model Quest` in schema.prisma expects. The version that stood here typed the column as
-- TEXT, so even had the ordering been the other way round, Prisma Client would have read every
-- quest's status as a plain string against an enum field.
--
-- The file is kept as a no-op rather than deleted: the name is part of the recorded migration
-- history, and removing it would make `migrate status` report a missing migration on any
-- database that has the row.
--
-- What "quest" is, and why it exists separately from "manager_task", is documented in
-- 20260903111619_manager_quests/migration.sql.

SELECT 1;
